name: Create ZIP on Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        ZIP_NAME="${{ github.repository##*/ }}-${{ github.ref_name%-datapack }}.zip"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r $ZIP_NAME . -x ".git/*" ".github/*"

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ZIP_NAME }}
        path: ${{ env.ZIP_NAME }}
