name: Create ZIP on Push

on:
  push:
    branches:
      - datapack  # Passe den Branch-Namen an, falls nötig

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        zip -r my-datapack.zip . -x ".git/*" ".github/*"

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-datapack
        path: my-datapack.zip
