name: Create ZIP on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        repo_name=$(basename $GITHUB_REPOSITORY)
        zip -r "${repo_name}.zip" . -x ".git/*" ".github/*"

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.event.repository.name }}.zip
