name: Create ZIP on Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Version Number
      run: echo "VERSION_NUMBER=$(echo ${GITHUB_REF##*/} | sed 's/-datapack//')" >> $GITHUB_ENV

    - name: Create ZIP
      run: |
        ZIP_NAME="$(basename $GITHUB_REPOSITORY)-${VERSION_NUMBER}.zip"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r $ZIP_NAME . -x ".git/*" ".github/*"

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ZIP_NAME }}
        path: ${{ env.ZIP_NAME }}
