name: Create ZIP on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        REPO_NAME=$(basename "$GITHUB_REPOSITORY")
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr / -)
        ZIP_NAME="${REPO_NAME}-${BRANCH_NAME}.zip"
        zip -r "$ZIP_NAME" . -x ".git/*" ".github/*"
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-datapack
        path: ${{ github.workspace }}/${{ env.ZIP_NAME }}
