name: Create ZIP on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        ZIP_NAME="${GITHUB_REPOSITORY##*/}-${GITHUB_REF_NAME}.zip"
        zip -r $ZIP_NAME . -x ".git/*" ".github/*"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ZIP_NAME }}
        path: ${{ env.ZIP_NAME }}
