name: Create ZIP on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Version Number
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF##*/})
        VERSION_NUMBER=$(echo $BRANCH_NAME | sed 's/-datapack//')
        echo "VERSION_NUMBER=${VERSION_NUMBER}" >> $GITHUB_ENV

    - name: Create ZIP
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        ZIP_NAME="${REPO_NAME}-${VERSION_NUMBER}.zip"
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
        zip -r $ZIP_NAME . -x ".git/*" ".github/*"

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ZIP_NAME }}
        path: ${{ env.ZIP_NAME }}
