name: Zip Datapack

on:
  push:
    branches:
      - 1.7-datapack  # Ersetze dies mit dem Namen deines Branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create ZIP file
      run: zip -r datapack.zip ./*

    - name: Upload ZIP file
      uses: actions/upload-artifact@v2
      with:
        name: datapack
        path: datapack.zip
