name: Create ZIP on Push

on:
  push:

jobs:
  build:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        zip -r "${{ github.repository }}.zip" . -x ".git/*" ".github/*"

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.repository }}
        path: "${{ github.repository }}.zip"
