name: Create ZIP on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        zip -r datapack.zip . -x ".git/*" ".github/*"

    - name: Set Artifact Name
      id: set-artifact-name
      run: echo "artifact_name=${GITHUB_REPOSITORY}-${GITHUB_REF_NAME/-datapack/}" >> $GITHUB_ENV

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifact_name }}
        path: datapack.zip
