name: Create ZIP on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        zip -r datapack.zip . -x ".git/*" ".github/*"

    - name: Set Artifact Name
      id: set-artifact-name
      run: |
        # Extract the basename of the repository
        repo_name=$(basename $GITHUB_REPOSITORY)
        # Remove `-datapack` from branch name if present
        artifact_name="${repo_name}-${GITHUB_REF_NAME/-datapack/}"
        # Set the artifact name as an environment variable
        echo "artifact_name=${artifact_name}" >> $GITHUB_ENV

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifact_name }}
        path: datapack.zip
